version: '3.3'

services:  
  postgres_db:
#      build: .
      image: postgres:10.0-alpine
      volumes:
        - ./database:/database
      environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=admin
        - POSTGRES_PASSWORD=docker
      ports:
        - 5432:5432