# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI_QT.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(955, 760)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 481, 311))
        self.tabWidget.setToolTip("")
        self.tabWidget.setToolTipDuration(-1)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.pushButton_delete100 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_delete100.setGeometry(QtCore.QRect(10, 180, 91, 21))
        self.pushButton_delete100.setToolTipDuration(-1)
        self.pushButton_delete100.setObjectName("pushButton_delete100")
        self.pushButton_deleteSelected = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_deleteSelected.setGeometry(QtCore.QRect(10, 240, 91, 23))
        self.pushButton_deleteSelected.setStyleSheet("background-color: qlineargradient(spread:reflect, x1:0.5, y1:0.5, x2:0, y2:0.028, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(255, 144, 144, 255));")
        self.pushButton_deleteSelected.setObjectName("pushButton_deleteSelected")
        self.pushButton_delete500 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_delete500.setGeometry(QtCore.QRect(10, 210, 91, 21))
        self.pushButton_delete500.setToolTipDuration(-1)
        self.pushButton_delete500.setObjectName("pushButton_delete500")
        self.pushButton_merge_selected = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_merge_selected.setGeometry(QtCore.QRect(10, 40, 91, 23))
        self.pushButton_merge_selected.setToolTipDuration(-1)
        self.pushButton_merge_selected.setObjectName("pushButton_merge_selected")
        self.frame = QtWidgets.QFrame(self.tab_2)
        self.frame.setGeometry(QtCore.QRect(0, 150, 111, 121))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setObjectName("frame")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(30, 10, 47, 13))
        self.label_3.setObjectName("label_3")
        self.pushButton_load_selected_csv = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_load_selected_csv.setGeometry(QtCore.QRect(10, 10, 91, 23))
        self.pushButton_load_selected_csv.setObjectName("pushButton_load_selected_csv")
        self.frame.raise_()
        self.pushButton_delete100.raise_()
        self.pushButton_deleteSelected.raise_()
        self.pushButton_delete500.raise_()
        self.pushButton_merge_selected.raise_()
        self.pushButton_load_selected_csv.raise_()
        self.tabWidget.addTab(self.tab_2, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.pushButton_collect1 = QtWidgets.QPushButton(self.tab)
        self.pushButton_collect1.setGeometry(QtCore.QRect(10, 10, 141, 23))
        self.pushButton_collect1.setObjectName("pushButton_collect1")
        self.pushButton_collect10 = QtWidgets.QPushButton(self.tab)
        self.pushButton_collect10.setGeometry(QtCore.QRect(10, 40, 141, 23))
        self.pushButton_collect10.setObjectName("pushButton_collect10")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(260, 10, 81, 21))
        self.label.setObjectName("label")
        self.label_login_status = QtWidgets.QLabel(self.tab)
        self.label_login_status.setGeometry(QtCore.QRect(320, 10, 91, 21))
        self.label_login_status.setMouseTracking(False)
        self.label_login_status.setStyleSheet("background-color: rgb(255, 149, 151);\n"
"color: rgb(255, 255, 255);")
        self.label_login_status.setAlignment(QtCore.Qt.AlignCenter)
        self.label_login_status.setObjectName("label_login_status")
        self.pushButton_11111111111111 = QtWidgets.QPushButton(self.tab)
        self.pushButton_11111111111111.setGeometry(QtCore.QRect(10, 100, 141, 23))
        self.pushButton_11111111111111.setObjectName("pushButton_11111111111111")
        self.tabWidget.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.pushButton_export_DF = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_export_DF.setGeometry(QtCore.QRect(10, 10, 91, 23))
        self.pushButton_export_DF.setObjectName("pushButton_export_DF")
        self.lineEdit_DF_comment = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_DF_comment.setGeometry(QtCore.QRect(110, 10, 133, 23))
        self.lineEdit_DF_comment.setObjectName("lineEdit_DF_comment")
        self.frame_4 = QtWidgets.QFrame(self.tab_3)
        self.frame_4.setGeometry(QtCore.QRect(0, 100, 311, 191))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_4.setObjectName("frame_4")
        self.label_6 = QtWidgets.QLabel(self.frame_4)
        self.label_6.setGeometry(QtCore.QRect(0, 0, 91, 20))
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.pushButton_export_DF_6 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_export_DF_6.setGeometry(QtCore.QRect(10, 20, 91, 23))
        self.pushButton_export_DF_6.setObjectName("pushButton_export_DF_6")
        self.lineEdit_DF_comment_2 = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_DF_comment_2.setGeometry(QtCore.QRect(10, 50, 91, 23))
        self.lineEdit_DF_comment_2.setObjectName("lineEdit_DF_comment_2")
        self.pushButton_export_DF_10 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_export_DF_10.setGeometry(QtCore.QRect(110, 20, 91, 23))
        self.pushButton_export_DF_10.setObjectName("pushButton_export_DF_10")
        self.lineEdit_DF_comment_6 = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_DF_comment_6.setGeometry(QtCore.QRect(110, 50, 91, 23))
        self.lineEdit_DF_comment_6.setObjectName("lineEdit_DF_comment_6")
        self.pushButton_export_DF_11 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_export_DF_11.setGeometry(QtCore.QRect(110, 80, 91, 23))
        self.pushButton_export_DF_11.setObjectName("pushButton_export_DF_11")
        self.pushButton_export_DF_9 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_export_DF_9.setGeometry(QtCore.QRect(10, 80, 91, 23))
        self.pushButton_export_DF_9.setObjectName("pushButton_export_DF_9")
        self.lineEdit_DF_comment_7 = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_DF_comment_7.setGeometry(QtCore.QRect(10, 110, 91, 23))
        self.lineEdit_DF_comment_7.setObjectName("lineEdit_DF_comment_7")
        self.lineEdit_DF_comment_5 = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_DF_comment_5.setGeometry(QtCore.QRect(110, 110, 91, 23))
        self.lineEdit_DF_comment_5.setObjectName("lineEdit_DF_comment_5")
        self.pushButton_export_DF_2 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_export_DF_2.setGeometry(QtCore.QRect(210, 20, 91, 23))
        self.pushButton_export_DF_2.setObjectName("pushButton_export_DF_2")
        self.pushButton_export_DF_3 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_export_DF_3.setGeometry(QtCore.QRect(210, 50, 91, 23))
        self.pushButton_export_DF_3.setObjectName("pushButton_export_DF_3")
        self.frame_3 = QtWidgets.QFrame(self.tab_3)
        self.frame_3.setGeometry(QtCore.QRect(310, 0, 171, 291))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_3.setObjectName("frame_3")
        self.pushButton_load_selected_csv_2 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_load_selected_csv_2.setGeometry(QtCore.QRect(70, 0, 91, 23))
        self.pushButton_load_selected_csv_2.setObjectName("pushButton_load_selected_csv_2")
        self.pushButton_reload_DF = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_reload_DF.setGeometry(QtCore.QRect(70, 30, 91, 23))
        self.pushButton_reload_DF.setObjectName("pushButton_reload_DF")
        self.pushButton_showTweets = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_showTweets.setGeometry(QtCore.QRect(70, 60, 91, 23))
        self.pushButton_showTweets.setObjectName("pushButton_showTweets")
        self.pushButton_export_DF_7 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_export_DF_7.setGeometry(QtCore.QRect(10, 40, 91, 23))
        self.pushButton_export_DF_7.setObjectName("pushButton_export_DF_7")
        self.lineEdit_DF_comment_3 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_DF_comment_3.setGeometry(QtCore.QRect(110, 40, 31, 23))
        self.lineEdit_DF_comment_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_DF_comment_3.setObjectName("lineEdit_DF_comment_3")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tabWidget.addTab(self.tab_4, "")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 320, 91, 16))
        self.label_2.setObjectName("label_2")
        self.treeView = QtWidgets.QTreeView(self.centralwidget)
        self.treeView.setGeometry(QtCore.QRect(500, 30, 441, 281))
        self.treeView.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.treeView.setObjectName("treeView")
        self.plainTextEdit_info = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_info.setGeometry(QtCore.QRect(10, 350, 481, 361))
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        self.plainTextEdit_info.setFont(font)
        self.plainTextEdit_info.setStyleSheet("background-color: rgb(220, 220, 220);\n"
"\n"
"")
        self.plainTextEdit_info.setFrameShape(QtWidgets.QFrame.Panel)
        self.plainTextEdit_info.setFrameShadow(QtWidgets.QFrame.Plain)
        self.plainTextEdit_info.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.plainTextEdit_info.setObjectName("plainTextEdit_info")
        self.textEdit_log = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_log.setGeometry(QtCore.QRect(500, 350, 441, 361))
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        self.textEdit_log.setFont(font)
        self.textEdit_log.setFrameShape(QtWidgets.QFrame.Box)
        self.textEdit_log.setFrameShadow(QtWidgets.QFrame.Raised)
        self.textEdit_log.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.textEdit_log.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.textEdit_log.setLineWrapColumnOrWidth(0)
        self.textEdit_log.setObjectName("textEdit_log")
        self.pushButton_clear_log = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_clear_log.setGeometry(QtCore.QRect(860, 320, 81, 23))
        self.pushButton_clear_log.setStyleSheet("background-color: qlineargradient(spread:reflect, x1:0.5, y1:0.5, x2:0, y2:0.028, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(255, 144, 144, 255));")
        self.pushButton_clear_log.setObjectName("pushButton_clear_log")
        self.pushButton_Info_screenLog = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Info_screenLog.setGeometry(QtCore.QRect(360, 320, 121, 23))
        self.pushButton_Info_screenLog.setStyleSheet("")
        self.pushButton_Info_screenLog.setObjectName("pushButton_Info_screenLog")
        self.pushButton_check_threads = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_check_threads.setGeometry(QtCore.QRect(500, 320, 91, 23))
        self.pushButton_check_threads.setStyleSheet("")
        self.pushButton_check_threads.setObjectName("pushButton_check_threads")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 955, 21))
        self.menubar.setObjectName("menubar")
        self.menuAcc = QtWidgets.QMenu(self.menubar)
        self.menuAcc.setObjectName("menuAcc")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        self.menuAnalyze = QtWidgets.QMenu(self.menubar)
        self.menuAnalyze.setObjectName("menuAnalyze")
        self.menuTask = QtWidgets.QMenu(self.menubar)
        self.menuTask.setObjectName("menuTask")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionLogin = QtWidgets.QAction(MainWindow)
        self.actionLogin.setObjectName("actionLogin")
        self.actionWho_am_I = QtWidgets.QAction(MainWindow)
        self.actionWho_am_I.setObjectName("actionWho_am_I")
        self.actionabout = QtWidgets.QAction(MainWindow)
        self.actionabout.setObjectName("actionabout")
        self.actionRefresh_GUI = QtWidgets.QAction(MainWindow)
        self.actionRefresh_GUI.setObjectName("actionRefresh_GUI")
        self.actionCheck_Status = QtWidgets.QAction(MainWindow)
        self.actionCheck_Status.setObjectName("actionCheck_Status")
        self.menuAcc.addAction(self.actionLogin)
        self.menuAcc.addAction(self.actionWho_am_I)
        self.menuAcc.addSeparator()
        self.menuAcc.addAction(self.actionRefresh_GUI)
        self.menuAbout.addAction(self.actionabout)
        self.menuTask.addAction(self.actionCheck_Status)
        self.menubar.addAction(self.menuAcc.menuAction())
        self.menubar.addAction(self.menuAnalyze.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())
        self.menubar.addAction(self.menuTask.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_delete100.setToolTip(_translate("MainWindow", "Delete CSV files that have less than 100 Tweets"))
        self.pushButton_delete100.setText(_translate("MainWindow", "Delete < 100"))
        self.pushButton_deleteSelected.setToolTip(_translate("MainWindow", "Delete files selected in Tree"))
        self.pushButton_deleteSelected.setText(_translate("MainWindow", "Delete Selected"))
        self.pushButton_delete500.setToolTip(_translate("MainWindow", "Delete CSV files that have less than 500 Tweets"))
        self.pushButton_delete500.setText(_translate("MainWindow", "Delete < 500"))
        self.pushButton_merge_selected.setToolTip(_translate("MainWindow", "Merge Selected Files to new file."))
        self.pushButton_merge_selected.setText(_translate("MainWindow", "Merge Selected"))
        self.label_3.setText(_translate("MainWindow", "Cleanup:"))
        self.pushButton_load_selected_csv.setText(_translate("MainWindow", "Load selected"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Files"))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Manage Tweet Files in \'tweets\' directory"))
        self.pushButton_collect1.setText(_translate("MainWindow", "1 Chunk"))
        self.pushButton_collect10.setText(_translate("MainWindow", "10 Chunks : 10mins"))
        self.label.setText(_translate("MainWindow", "Logged in:"))
        self.label_login_status.setText(_translate("MainWindow", "Not logged in"))
        self.pushButton_11111111111111.setText(_translate("MainWindow", "10 Chunks : 10mins"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Request"))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Collect Tweets from tweeter"))
        self.pushButton_export_DF.setToolTip(_translate("MainWindow", "Save DF to .csv File"))
        self.pushButton_export_DF.setText(_translate("MainWindow", "Save DF"))
        self.lineEdit_DF_comment.setToolTip(_translate("MainWindow", "You can Add some comment to file name"))
        self.label_6.setText(_translate("MainWindow", "Filter DF"))
        self.pushButton_export_DF_6.setToolTip(_translate("MainWindow", "Save DF to .csv File"))
        self.pushButton_export_DF_6.setText(_translate("MainWindow", "User"))
        self.lineEdit_DF_comment_2.setToolTip(_translate("MainWindow", "You can Add some comment to file name"))
        self.pushButton_export_DF_10.setToolTip(_translate("MainWindow", "Save DF to .csv File"))
        self.pushButton_export_DF_10.setText(_translate("MainWindow", "TweetId"))
        self.lineEdit_DF_comment_6.setToolTip(_translate("MainWindow", "You can Add some comment to file name"))
        self.pushButton_export_DF_11.setToolTip(_translate("MainWindow", "Save DF to .csv File"))
        self.pushButton_export_DF_11.setText(_translate("MainWindow", "Words"))
        self.pushButton_export_DF_9.setToolTip(_translate("MainWindow", "Save DF to .csv File"))
        self.pushButton_export_DF_9.setText(_translate("MainWindow", "Text"))
        self.lineEdit_DF_comment_7.setToolTip(_translate("MainWindow", "You can Add some comment to file name"))
        self.lineEdit_DF_comment_5.setToolTip(_translate("MainWindow", "You can Add some comment to file name"))
        self.pushButton_export_DF_2.setToolTip(_translate("MainWindow", "Save DF to .csv File"))
        self.pushButton_export_DF_2.setText(_translate("MainWindow", "Lang PL"))
        self.pushButton_export_DF_3.setToolTip(_translate("MainWindow", "Save DF to .csv File"))
        self.pushButton_export_DF_3.setText(_translate("MainWindow", "Lang En"))
        self.pushButton_load_selected_csv_2.setToolTip(_translate("MainWindow", "Loads files from tree."))
        self.pushButton_load_selected_csv_2.setText(_translate("MainWindow", "Load selected"))
        self.pushButton_reload_DF.setToolTip(_translate("MainWindow", "Reload DF from same files again."))
        self.pushButton_reload_DF.setText(_translate("MainWindow", "Reload DF"))
        self.pushButton_showTweets.setToolTip(_translate("MainWindow", "Shows currently loaded DF"))
        self.pushButton_showTweets.setText(_translate("MainWindow", "Show DF"))
        self.pushButton_export_DF_7.setToolTip(_translate("MainWindow", "Split DF into X pieces and save."))
        self.pushButton_export_DF_7.setText(_translate("MainWindow", "Split DF"))
        self.lineEdit_DF_comment_3.setToolTip(_translate("MainWindow", "Number of pieces to split."))
        self.lineEdit_DF_comment_3.setText(_translate("MainWindow", "2"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Analyze CSV"))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Analyze loaded DF"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "NN Model"))
        self.label_2.setText(_translate("MainWindow", "Current info:"))
        self.plainTextEdit_info.setPlainText(_translate("MainWindow", "None"))
        self.textEdit_log.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Lucida Console\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\';\"><br /></p></body></html>"))
        self.pushButton_clear_log.setText(_translate("MainWindow", "Clear Log"))
        self.pushButton_Info_screenLog.setText(_translate("MainWindow", "Copy info To Log ->"))
        self.pushButton_check_threads.setText(_translate("MainWindow", "Check Threads"))
        self.menuAcc.setTitle(_translate("MainWindow", "Start"))
        self.menuAbout.setTitle(_translate("MainWindow", "About"))
        self.menuAnalyze.setTitle(_translate("MainWindow", "Analyze"))
        self.menuTask.setTitle(_translate("MainWindow", "Task"))
        self.actionLogin.setText(_translate("MainWindow", "Login"))
        self.actionWho_am_I.setText(_translate("MainWindow", "Who am I?"))
        self.actionabout.setText(_translate("MainWindow", "about"))
        self.actionRefresh_GUI.setText(_translate("MainWindow", "Refresh GUI"))
        self.actionCheck_Status.setText(_translate("MainWindow", "Check Status"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
