# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI_QT.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1025, 884)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 10, 411, 361))
        self.tabWidget.setToolTip("")
        self.tabWidget.setToolTipDuration(-1)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.pushButton_delete100 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_delete100.setGeometry(QtCore.QRect(10, 180, 91, 21))
        self.pushButton_delete100.setToolTipDuration(-1)
        self.pushButton_delete100.setObjectName("pushButton_delete100")
        self.pushButton_deleteSelected = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_deleteSelected.setGeometry(QtCore.QRect(10, 240, 91, 23))
        self.pushButton_deleteSelected.setStyleSheet("background-color: qlineargradient(spread:reflect, x1:0.5, y1:0.5, x2:0, y2:0.028, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(255, 144, 144, 255));")
        self.pushButton_deleteSelected.setObjectName("pushButton_deleteSelected")
        self.pushButton_delete500 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_delete500.setGeometry(QtCore.QRect(10, 210, 91, 21))
        self.pushButton_delete500.setToolTipDuration(-1)
        self.pushButton_delete500.setObjectName("pushButton_delete500")
        self.pushButton_merge_selected = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_merge_selected.setGeometry(QtCore.QRect(10, 40, 91, 23))
        self.pushButton_merge_selected.setToolTipDuration(-1)
        self.pushButton_merge_selected.setObjectName("pushButton_merge_selected")
        self.frame = QtWidgets.QFrame(self.tab_2)
        self.frame.setGeometry(QtCore.QRect(0, 150, 111, 121))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setObjectName("frame")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(30, 10, 47, 13))
        self.label_3.setObjectName("label_3")
        self.pushButton_load_selected_csv = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_load_selected_csv.setGeometry(QtCore.QRect(10, 10, 91, 23))
        self.pushButton_load_selected_csv.setObjectName("pushButton_load_selected_csv")
        self.frame.raise_()
        self.pushButton_delete100.raise_()
        self.pushButton_deleteSelected.raise_()
        self.pushButton_delete500.raise_()
        self.pushButton_merge_selected.raise_()
        self.pushButton_load_selected_csv.raise_()
        self.tabWidget.addTab(self.tab_2, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.pushButton_collect1 = QtWidgets.QPushButton(self.tab)
        self.pushButton_collect1.setGeometry(QtCore.QRect(10, 10, 141, 23))
        self.pushButton_collect1.setObjectName("pushButton_collect1")
        self.pushButton_collect10 = QtWidgets.QPushButton(self.tab)
        self.pushButton_collect10.setGeometry(QtCore.QRect(10, 40, 141, 23))
        self.pushButton_collect10.setObjectName("pushButton_collect10")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(220, 10, 81, 21))
        self.label.setObjectName("label")
        self.label_login_status = QtWidgets.QLabel(self.tab)
        self.label_login_status.setGeometry(QtCore.QRect(220, 40, 91, 21))
        self.label_login_status.setMouseTracking(False)
        self.label_login_status.setStyleSheet("background-color: rgb(255, 149, 151);\n"
"color: rgb(255, 255, 255);")
        self.label_login_status.setAlignment(QtCore.Qt.AlignCenter)
        self.label_login_status.setObjectName("label_login_status")
        self.pushButton_11111111111111 = QtWidgets.QPushButton(self.tab)
        self.pushButton_11111111111111.setGeometry(QtCore.QRect(10, 70, 141, 23))
        self.pushButton_11111111111111.setObjectName("pushButton_11111111111111")
        self.pushButton_Request_Status = QtWidgets.QPushButton(self.tab)
        self.pushButton_Request_Status.setGeometry(QtCore.QRect(10, 100, 141, 23))
        self.pushButton_Request_Status.setObjectName("pushButton_Request_Status")
        self.lineEdit_request_statusId = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_request_statusId.setGeometry(QtCore.QRect(160, 100, 151, 23))
        self.lineEdit_request_statusId.setObjectName("lineEdit_request_statusId")
        self.tabWidget.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.pushButton_export_DF = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_export_DF.setGeometry(QtCore.QRect(10, 10, 91, 23))
        self.pushButton_export_DF.setObjectName("pushButton_export_DF")
        self.lineEdit_DF_comment = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_DF_comment.setGeometry(QtCore.QRect(110, 10, 133, 23))
        self.lineEdit_DF_comment.setObjectName("lineEdit_DF_comment")
        self.frame_4 = QtWidgets.QFrame(self.tab_3)
        self.frame_4.setGeometry(QtCore.QRect(-10, 100, 421, 251))
        self.frame_4.setStyleSheet("")
        self.frame_4.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_4.setObjectName("frame_4")
        self.label_6 = QtWidgets.QLabel(self.frame_4)
        self.label_6.setGeometry(QtCore.QRect(10, 0, 91, 20))
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.pushButton_export_DF_6 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_export_DF_6.setGeometry(QtCore.QRect(20, 20, 91, 23))
        self.pushButton_export_DF_6.setObjectName("pushButton_export_DF_6")
        self.lineEdit_DF_comment_2 = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_DF_comment_2.setGeometry(QtCore.QRect(20, 50, 91, 23))
        self.lineEdit_DF_comment_2.setObjectName("lineEdit_DF_comment_2")
        self.pushButton_export_DF_10 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_export_DF_10.setGeometry(QtCore.QRect(120, 20, 91, 23))
        self.pushButton_export_DF_10.setObjectName("pushButton_export_DF_10")
        self.lineEdit_DF_comment_6 = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_DF_comment_6.setGeometry(QtCore.QRect(120, 50, 91, 23))
        self.lineEdit_DF_comment_6.setObjectName("lineEdit_DF_comment_6")
        self.pushButton_export_DF_11 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_export_DF_11.setGeometry(QtCore.QRect(120, 80, 91, 23))
        self.pushButton_export_DF_11.setObjectName("pushButton_export_DF_11")
        self.pushButton_export_DF_9 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_export_DF_9.setGeometry(QtCore.QRect(20, 80, 91, 23))
        self.pushButton_export_DF_9.setObjectName("pushButton_export_DF_9")
        self.lineEdit_DF_comment_7 = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_DF_comment_7.setGeometry(QtCore.QRect(20, 110, 91, 23))
        self.lineEdit_DF_comment_7.setObjectName("lineEdit_DF_comment_7")
        self.lineEdit_DF_comment_5 = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_DF_comment_5.setGeometry(QtCore.QRect(120, 110, 91, 23))
        self.lineEdit_DF_comment_5.setObjectName("lineEdit_DF_comment_5")
        self.pushButton_FilterDF_Lang_Polish = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_FilterDF_Lang_Polish.setGeometry(QtCore.QRect(220, 20, 91, 23))
        self.pushButton_FilterDF_Lang_Polish.setObjectName("pushButton_FilterDF_Lang_Polish")
        self.pushButton_FilterDF_Lang_English = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_FilterDF_Lang_English.setGeometry(QtCore.QRect(220, 50, 91, 23))
        self.pushButton_FilterDF_Lang_English.setObjectName("pushButton_FilterDF_Lang_English")
        self.frame_5 = QtWidgets.QFrame(self.frame_4)
        self.frame_5.setGeometry(QtCore.QRect(0, 140, 421, 101))
        self.frame_5.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_5.setObjectName("frame_5")
        self.pushButton_export_DF_18 = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_export_DF_18.setGeometry(QtCore.QRect(20, 10, 91, 23))
        self.pushButton_export_DF_18.setObjectName("pushButton_export_DF_18")
        self.lineEdit_DF_comment_8 = QtWidgets.QLineEdit(self.frame_5)
        self.lineEdit_DF_comment_8.setGeometry(QtCore.QRect(270, 10, 41, 23))
        self.lineEdit_DF_comment_8.setObjectName("lineEdit_DF_comment_8")
        self.lineEdit_DF_comment_10 = QtWidgets.QLineEdit(self.frame_5)
        self.lineEdit_DF_comment_10.setGeometry(QtCore.QRect(220, 10, 41, 23))
        self.lineEdit_DF_comment_10.setObjectName("lineEdit_DF_comment_10")
        self.lineEdit_DF_comment_15 = QtWidgets.QLineEdit(self.frame_5)
        self.lineEdit_DF_comment_15.setGeometry(QtCore.QRect(170, 10, 41, 23))
        self.lineEdit_DF_comment_15.setObjectName("lineEdit_DF_comment_15")
        self.lineEdit_DF_comment_9 = QtWidgets.QLineEdit(self.frame_5)
        self.lineEdit_DF_comment_9.setGeometry(QtCore.QRect(270, 40, 41, 23))
        self.lineEdit_DF_comment_9.setObjectName("lineEdit_DF_comment_9")
        self.lineEdit_DF_comment_16 = QtWidgets.QLineEdit(self.frame_5)
        self.lineEdit_DF_comment_16.setGeometry(QtCore.QRect(170, 40, 41, 23))
        self.lineEdit_DF_comment_16.setObjectName("lineEdit_DF_comment_16")
        self.lineEdit_DF_comment_17 = QtWidgets.QLineEdit(self.frame_5)
        self.lineEdit_DF_comment_17.setGeometry(QtCore.QRect(220, 40, 41, 23))
        self.lineEdit_DF_comment_17.setObjectName("lineEdit_DF_comment_17")
        self.pushButton_export_DF_26 = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_export_DF_26.setGeometry(QtCore.QRect(20, 40, 91, 23))
        self.pushButton_export_DF_26.setObjectName("pushButton_export_DF_26")
        self.label_4 = QtWidgets.QLabel(self.frame_5)
        self.label_4.setGeometry(QtCore.QRect(170, 70, 41, 20))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.frame_5)
        self.label_5.setGeometry(QtCore.QRect(220, 70, 41, 20))
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_7 = QtWidgets.QLabel(self.frame_5)
        self.label_7.setGeometry(QtCore.QRect(270, 70, 41, 20))
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.label_9 = QtWidgets.QLabel(self.frame_5)
        self.label_9.setGeometry(QtCore.QRect(130, 10, 41, 20))
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.frame_5)
        self.label_10.setGeometry(QtCore.QRect(130, 40, 41, 20))
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.pushButton_FilterDF_Lang_Other = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_FilterDF_Lang_Other.setGeometry(QtCore.QRect(220, 80, 91, 23))
        self.pushButton_FilterDF_Lang_Other.setObjectName("pushButton_FilterDF_Lang_Other")
        self.lineEdit_FilterLangOther = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_FilterLangOther.setGeometry(QtCore.QRect(220, 110, 91, 23))
        self.lineEdit_FilterLangOther.setObjectName("lineEdit_FilterLangOther")
        self.pushButton_FilterDF_by_Key = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_FilterDF_by_Key.setGeometry(QtCore.QRect(320, 80, 91, 23))
        self.pushButton_FilterDF_by_Key.setObjectName("pushButton_FilterDF_by_Key")
        self.lineEdit_filterKeyinput = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_filterKeyinput.setGeometry(QtCore.QRect(320, 110, 91, 23))
        self.lineEdit_filterKeyinput.setObjectName("lineEdit_filterKeyinput")
        self.pushButton_export_DF_7 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_export_DF_7.setGeometry(QtCore.QRect(10, 40, 91, 23))
        self.pushButton_export_DF_7.setObjectName("pushButton_export_DF_7")
        self.lineEdit_DF_comment_3 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_DF_comment_3.setGeometry(QtCore.QRect(110, 40, 31, 23))
        self.lineEdit_DF_comment_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_DF_comment_3.setObjectName("lineEdit_DF_comment_3")
        self.tabWidget.addTab(self.tab_3, "")
        self.Analyze = QtWidgets.QWidget()
        self.Analyze.setObjectName("Analyze")
        self.tabWidget.addTab(self.Analyze, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tabWidget.addTab(self.tab_4, "")
        self.treeView = QtWidgets.QTreeView(self.centralwidget)
        self.treeView.setGeometry(QtCore.QRect(600, 10, 411, 361))
        self.treeView.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.treeView.setObjectName("treeView")
        self.plainTextEdit_info = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_info.setGeometry(QtCore.QRect(10, 380, 571, 461))
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        self.plainTextEdit_info.setFont(font)
        self.plainTextEdit_info.setStyleSheet("background-color: rgb(220, 220, 220);\n"
"\n"
"")
        self.plainTextEdit_info.setFrameShape(QtWidgets.QFrame.Panel)
        self.plainTextEdit_info.setFrameShadow(QtWidgets.QFrame.Plain)
        self.plainTextEdit_info.setLineWidth(1)
        self.plainTextEdit_info.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.plainTextEdit_info.setObjectName("plainTextEdit_info")
        self.textEdit_log = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_log.setGeometry(QtCore.QRect(590, 410, 421, 431))
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        self.textEdit_log.setFont(font)
        self.textEdit_log.setFrameShape(QtWidgets.QFrame.Box)
        self.textEdit_log.setFrameShadow(QtWidgets.QFrame.Raised)
        self.textEdit_log.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.textEdit_log.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.textEdit_log.setLineWrapColumnOrWidth(0)
        self.textEdit_log.setObjectName("textEdit_log")
        self.pushButton_clear_log = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_clear_log.setGeometry(QtCore.QRect(920, 380, 81, 23))
        self.pushButton_clear_log.setStyleSheet("background-color: qlineargradient(spread:reflect, x1:0.5, y1:0.5, x2:0, y2:0.028, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(255, 144, 144, 255));")
        self.pushButton_clear_log.setObjectName("pushButton_clear_log")
        self.pushButton_Info_screenLog = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Info_screenLog.setGeometry(QtCore.QRect(600, 380, 121, 23))
        self.pushButton_Info_screenLog.setStyleSheet("")
        self.pushButton_Info_screenLog.setObjectName("pushButton_Info_screenLog")
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(410, 10, 181, 361))
        self.frame_3.setStyleSheet("")
        self.frame_3.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_3.setObjectName("frame_3")
        self.pushButton_NextTweet = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_NextTweet.setGeometry(QtCore.QRect(90, 210, 81, 23))
        self.pushButton_NextTweet.setObjectName("pushButton_NextTweet")
        self.pushButton_PreviousTweet = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_PreviousTweet.setGeometry(QtCore.QRect(10, 210, 81, 23))
        self.pushButton_PreviousTweet.setObjectName("pushButton_PreviousTweet")
        self.pushButton_ShowTweet = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_ShowTweet.setGeometry(QtCore.QRect(10, 180, 91, 23))
        self.pushButton_ShowTweet.setObjectName("pushButton_ShowTweet")
        self.pushButton_JumpToTweet = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_JumpToTweet.setGeometry(QtCore.QRect(10, 330, 91, 23))
        self.pushButton_JumpToTweet.setObjectName("pushButton_JumpToTweet")
        self.lineEdit_JumpToTweet = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_JumpToTweet.setGeometry(QtCore.QRect(110, 330, 51, 23))
        self.lineEdit_JumpToTweet.setObjectName("lineEdit_JumpToTweet")
        self.frame_6 = QtWidgets.QFrame(self.frame_3)
        self.frame_6.setGeometry(QtCore.QRect(0, 0, 181, 111))
        self.frame_6.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_6.setObjectName("frame_6")
        self.pushButton_load_selected_csv_2 = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_load_selected_csv_2.setGeometry(QtCore.QRect(10, 10, 91, 23))
        self.pushButton_load_selected_csv_2.setObjectName("pushButton_load_selected_csv_2")
        self.pushButton_reload_DF = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_reload_DF.setGeometry(QtCore.QRect(10, 40, 91, 23))
        self.pushButton_reload_DF.setObjectName("pushButton_reload_DF")
        self.pushButton_showTweets = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_showTweets.setGeometry(QtCore.QRect(10, 150, 91, 23))
        self.pushButton_showTweets.setStyleSheet("")
        self.pushButton_showTweets.setObjectName("pushButton_showTweets")
        self.pushButton_check_threads = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_check_threads.setGeometry(QtCore.QRect(820, 380, 91, 23))
        self.pushButton_check_threads.setStyleSheet("")
        self.pushButton_check_threads.setObjectName("pushButton_check_threads")
        self.tabWidget.raise_()
        self.frame_3.raise_()
        self.treeView.raise_()
        self.plainTextEdit_info.raise_()
        self.textEdit_log.raise_()
        self.pushButton_clear_log.raise_()
        self.pushButton_Info_screenLog.raise_()
        self.pushButton_check_threads.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1025, 21))
        self.menubar.setObjectName("menubar")
        self.actionMenuAuth = QtWidgets.QMenu(self.menubar)
        self.actionMenuAuth.setObjectName("actionMenuAuth")
        self.actionMenuRefresh_Gui = QtWidgets.QMenu(self.menubar)
        self.actionMenuRefresh_Gui.setObjectName("actionMenuRefresh_Gui")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionLogin = QtWidgets.QAction(MainWindow)
        self.actionLogin.setObjectName("actionLogin")
        self.actionRefresh_GUI = QtWidgets.QAction(MainWindow)
        self.actionRefresh_GUI.setObjectName("actionRefresh_GUI")
        self.actionWho_am_I = QtWidgets.QAction(MainWindow)
        self.actionWho_am_I.setObjectName("actionWho_am_I")
        self.actionTweet_Description = QtWidgets.QAction(MainWindow)
        self.actionTweet_Description.setObjectName("actionTweet_Description")
        self.actionMenuAuth.addAction(self.actionLogin)
        self.actionMenuAuth.addAction(self.actionWho_am_I)
        self.actionMenuRefresh_Gui.addAction(self.actionRefresh_GUI)
        self.menuHelp.addAction(self.actionTweet_Description)
        self.menubar.addAction(self.actionMenuAuth.menuAction())
        self.menubar.addAction(self.actionMenuRefresh_Gui.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_delete100.setToolTip(_translate("MainWindow", "Delete CSV files that have less than 100 Tweets"))
        self.pushButton_delete100.setText(_translate("MainWindow", "Delete < 100"))
        self.pushButton_deleteSelected.setToolTip(_translate("MainWindow", "Delete files selected in Tree"))
        self.pushButton_deleteSelected.setText(_translate("MainWindow", "Delete Selected"))
        self.pushButton_delete500.setToolTip(_translate("MainWindow", "Delete CSV files that have less than 500 Tweets"))
        self.pushButton_delete500.setText(_translate("MainWindow", "Delete < 500"))
        self.pushButton_merge_selected.setToolTip(_translate("MainWindow", "Merge Selected Files to new file."))
        self.pushButton_merge_selected.setText(_translate("MainWindow", "Merge Selected"))
        self.label_3.setText(_translate("MainWindow", "Cleanup:"))
        self.pushButton_load_selected_csv.setText(_translate("MainWindow", "Load selected"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Files"))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Manage Tweet Files in \'tweets\' directory"))
        self.pushButton_collect1.setText(_translate("MainWindow", "1 Chunk"))
        self.pushButton_collect10.setText(_translate("MainWindow", "10 Chunks : 10mins"))
        self.label.setText(_translate("MainWindow", "Logged in:"))
        self.label_login_status.setText(_translate("MainWindow", "Not logged in"))
        self.pushButton_11111111111111.setText(_translate("MainWindow", "Request parent Tweets"))
        self.pushButton_Request_Status.setText(_translate("MainWindow", "Request status"))
        self.lineEdit_request_statusId.setToolTip(_translate("MainWindow", "Input index for Jump button."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Request"))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Collect Tweets from tweeter"))
        self.pushButton_export_DF.setToolTip(_translate("MainWindow", "Save DF to .csv File"))
        self.pushButton_export_DF.setText(_translate("MainWindow", "Save DF"))
        self.lineEdit_DF_comment.setToolTip(_translate("MainWindow", "You can Add some comment to file name"))
        self.label_6.setText(_translate("MainWindow", "Filter DF"))
        self.pushButton_export_DF_6.setToolTip(_translate("MainWindow", "Save DF to .csv File"))
        self.pushButton_export_DF_6.setText(_translate("MainWindow", "User"))
        self.lineEdit_DF_comment_2.setToolTip(_translate("MainWindow", "You can Add some comment to file name"))
        self.pushButton_export_DF_10.setToolTip(_translate("MainWindow", "Save DF to .csv File"))
        self.pushButton_export_DF_10.setText(_translate("MainWindow", "TweetId"))
        self.lineEdit_DF_comment_6.setToolTip(_translate("MainWindow", "You can Add some comment to file name"))
        self.pushButton_export_DF_11.setToolTip(_translate("MainWindow", "Save DF to .csv File"))
        self.pushButton_export_DF_11.setText(_translate("MainWindow", "Words"))
        self.pushButton_export_DF_9.setToolTip(_translate("MainWindow", "Save DF to .csv File"))
        self.pushButton_export_DF_9.setText(_translate("MainWindow", "Text"))
        self.lineEdit_DF_comment_7.setToolTip(_translate("MainWindow", "You can Add some comment to file name"))
        self.lineEdit_DF_comment_5.setToolTip(_translate("MainWindow", "You can Add some comment to file name"))
        self.pushButton_FilterDF_Lang_Polish.setToolTip(_translate("MainWindow", "Filter DF, polish"))
        self.pushButton_FilterDF_Lang_Polish.setText(_translate("MainWindow", "Lang PL"))
        self.pushButton_FilterDF_Lang_English.setToolTip(_translate("MainWindow", "Filter DF, english"))
        self.pushButton_FilterDF_Lang_English.setText(_translate("MainWindow", "Lang En"))
        self.pushButton_export_DF_18.setToolTip(_translate("MainWindow", "Save DF to .csv File"))
        self.pushButton_export_DF_18.setText(_translate("MainWindow", "Time range"))
        self.lineEdit_DF_comment_8.setToolTip(_translate("MainWindow", "You can Add some comment to file name"))
        self.lineEdit_DF_comment_10.setToolTip(_translate("MainWindow", "You can Add some comment to file name"))
        self.lineEdit_DF_comment_15.setToolTip(_translate("MainWindow", "You can Add some comment to file name"))
        self.lineEdit_DF_comment_9.setToolTip(_translate("MainWindow", "You can Add some comment to file name"))
        self.lineEdit_DF_comment_16.setToolTip(_translate("MainWindow", "You can Add some comment to file name"))
        self.lineEdit_DF_comment_17.setToolTip(_translate("MainWindow", "You can Add some comment to file name"))
        self.pushButton_export_DF_26.setToolTip(_translate("MainWindow", "Save DF to .csv File"))
        self.pushButton_export_DF_26.setText(_translate("MainWindow", "Age"))
        self.label_4.setText(_translate("MainWindow", "H"))
        self.label_5.setText(_translate("MainWindow", "M"))
        self.label_7.setText(_translate("MainWindow", "S"))
        self.label_9.setText(_translate("MainWindow", "from:"))
        self.label_10.setText(_translate("MainWindow", "to:"))
        self.pushButton_FilterDF_Lang_Other.setToolTip(_translate("MainWindow", "Filter DF, put language below"))
        self.pushButton_FilterDF_Lang_Other.setText(_translate("MainWindow", "Lang"))
        self.lineEdit_FilterLangOther.setToolTip(_translate("MainWindow", "input for Lang Button"))
        self.pushButton_FilterDF_by_Key.setToolTip(_translate("MainWindow", "Filter tweets with valused instead of None, put category"))
        self.pushButton_FilterDF_by_Key.setText(_translate("MainWindow", "Find Key"))
        self.lineEdit_filterKeyinput.setToolTip(_translate("MainWindow", "Key input"))
        self.pushButton_export_DF_7.setToolTip(_translate("MainWindow", "Split DF into X pieces and saves."))
        self.pushButton_export_DF_7.setText(_translate("MainWindow", "Split DF"))
        self.lineEdit_DF_comment_3.setToolTip(_translate("MainWindow", "Number of pieces to split."))
        self.lineEdit_DF_comment_3.setText(_translate("MainWindow", "2"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Prepare Data"))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Analyze loaded DF"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Analyze), _translate("MainWindow", "Analyze"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "NN Model"))
        self.plainTextEdit_info.setPlainText(_translate("MainWindow", "None"))
        self.textEdit_log.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Lucida Console\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\';\"><br /></p></body></html>"))
        self.pushButton_clear_log.setText(_translate("MainWindow", "Clear Log"))
        self.pushButton_Info_screenLog.setText(_translate("MainWindow", "Copy info To Log ->"))
        self.pushButton_NextTweet.setToolTip(_translate("MainWindow", "Show next Tweet from DF"))
        self.pushButton_NextTweet.setText(_translate("MainWindow", "Next >>"))
        self.pushButton_PreviousTweet.setToolTip(_translate("MainWindow", "Show previous Tweet from DF"))
        self.pushButton_PreviousTweet.setText(_translate("MainWindow", "<< Prev"))
        self.pushButton_ShowTweet.setToolTip(_translate("MainWindow", "Show first Tweet from DF"))
        self.pushButton_ShowTweet.setText(_translate("MainWindow", "Show Tweet"))
        self.pushButton_JumpToTweet.setToolTip(_translate("MainWindow", "Jumps to Tweet in DF, define index in box."))
        self.pushButton_JumpToTweet.setText(_translate("MainWindow", "Jump"))
        self.lineEdit_JumpToTweet.setToolTip(_translate("MainWindow", "Input index for Jump button."))
        self.pushButton_load_selected_csv_2.setToolTip(_translate("MainWindow", "Loads files from tree."))
        self.pushButton_load_selected_csv_2.setText(_translate("MainWindow", "Load selected"))
        self.pushButton_reload_DF.setToolTip(_translate("MainWindow", "Reload DF from the same files again."))
        self.pushButton_reload_DF.setText(_translate("MainWindow", "Reload DF"))
        self.pushButton_showTweets.setToolTip(_translate("MainWindow", "Shows currently loaded DF"))
        self.pushButton_showTweets.setText(_translate("MainWindow", "DF Info"))
        self.pushButton_check_threads.setToolTip(_translate("MainWindow", "Check currently runing threads and print status."))
        self.pushButton_check_threads.setText(_translate("MainWindow", "Check Threads"))
        self.actionMenuAuth.setTitle(_translate("MainWindow", "Auth"))
        self.actionMenuRefresh_Gui.setTitle(_translate("MainWindow", "GUI"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionLogin.setText(_translate("MainWindow", "Login"))
        self.actionRefresh_GUI.setText(_translate("MainWindow", "Refresh"))
        self.actionWho_am_I.setText(_translate("MainWindow", "Who am I?"))
        self.actionTweet_Description.setText(_translate("MainWindow", "Tweet Description"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
