from sqlalchemy import Column, Integer, String
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()


class Tweets(Base):
    __tablename__ = 'tweets'
    id = Column(Integer, primary_key=True)
    timestamp = Column(Integer)
    contributors = Column(String)
    coordinates = Column(String)
    created_at = Column(String)
    current_user_retweet = Column(Integer)
    favorite_count = Column(Integer)
    favorited = Column(String)
    full_text = Column(String)
    geo = Column(String)
    hashtags = Column(String)
    id_str = Column(String)
    in_reply_to_screen_name = Column(String)
    in_reply_to_status_id = Column(Integer)
    in_reply_to_user_id = Column(Integer)
    lang = Column(String)
    location = Column(String)
    media = Column(String)
    place = Column(String)
    possibly_sensitive = Column(String)
    quoted_status = Column(String)
    quoted_status_id = Column(Integer)
    quoted_status_id_str = Column(String)
    retweet_count = Column(Integer)
    retweeted = Column(String)
    retweeted_status = Column(String)
    scopes = Column(String)
    source = Column(String)
    truncated = Column(String)
    urls = Column(String)
    user = Column(String)
    user_mentions = Column(String)
    withheld_copyright = Column(String)
    withheld_in_countries = Column(String)
    withheld_scope = Column(String)
    tweet_mode = Column(String)
