# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui/GUI_QT.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1090, 924)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.gridLayout.setObjectName("gridLayout")
        self.MainGrid = QtWidgets.QGridLayout()
        self.MainGrid.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.MainGrid.setContentsMargins(0, -1, -1, -1)
        self.MainGrid.setObjectName("MainGrid")
        self.grid_Small5 = QtWidgets.QGridLayout()
        self.grid_Small5.setObjectName("grid_Small5")
        self.checkBox_wrap_console = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_wrap_console.setChecked(True)
        self.checkBox_wrap_console.setObjectName("checkBox_wrap_console")
        self.grid_Small5.addWidget(self.checkBox_wrap_console, 4, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.grid_Small5.addItem(spacerItem, 6, 0, 1, 1)
        self.checkBox_HideEmptyValues = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_HideEmptyValues.setEnabled(False)
        self.checkBox_HideEmptyValues.setChecked(True)
        self.checkBox_HideEmptyValues.setObjectName("checkBox_HideEmptyValues")
        self.grid_Small5.addWidget(self.checkBox_HideEmptyValues, 2, 0, 1, 1)
        self.checkBox_DisplayShortUserinfo = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_DisplayShortUserinfo.setEnabled(False)
        self.checkBox_DisplayShortUserinfo.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkBox_DisplayShortUserinfo.setAutoFillBackground(False)
        self.checkBox_DisplayShortUserinfo.setChecked(True)
        self.checkBox_DisplayShortUserinfo.setObjectName("checkBox_DisplayShortUserinfo")
        self.grid_Small5.addWidget(self.checkBox_DisplayShortUserinfo, 1, 0, 1, 1)
        self.checkBox_DisplayShortQuoteStatus = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_DisplayShortQuoteStatus.setEnabled(False)
        self.checkBox_DisplayShortQuoteStatus.setChecked(True)
        self.checkBox_DisplayShortQuoteStatus.setObjectName("checkBox_DisplayShortQuoteStatus")
        self.grid_Small5.addWidget(self.checkBox_DisplayShortQuoteStatus, 0, 0, 1, 1)
        self.checkBox_show_only_text = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_show_only_text.setObjectName("checkBox_show_only_text")
        self.grid_Small5.addWidget(self.checkBox_show_only_text, 3, 0, 1, 1)
        self.MainGrid.addLayout(self.grid_Small5, 2, 2, 3, 1)
        self.plainTextEdit_info = QtWidgets.QPlainTextEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.plainTextEdit_info.setFont(font)
        self.plainTextEdit_info.setStyleSheet("background-color: rgb(220, 220, 220);\n"
"\n"
"")
        self.plainTextEdit_info.setFrameShape(QtWidgets.QFrame.Panel)
        self.plainTextEdit_info.setFrameShadow(QtWidgets.QFrame.Plain)
        self.plainTextEdit_info.setLineWidth(1)
        self.plainTextEdit_info.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.plainTextEdit_info.setObjectName("plainTextEdit_info")
        self.MainGrid.addWidget(self.plainTextEdit_info, 1, 0, 4, 2)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setToolTip("")
        self.tabWidget.setToolTipDuration(-1)
        self.tabWidget.setObjectName("tabWidget")
        self.PrepareData = QtWidgets.QWidget()
        self.PrepareData.setObjectName("PrepareData")
        self.pushButton_export_DF = QtWidgets.QPushButton(self.PrepareData)
        self.pushButton_export_DF.setEnabled(True)
        self.pushButton_export_DF.setGeometry(QtCore.QRect(10, 10, 191, 21))
        self.pushButton_export_DF.setObjectName("pushButton_export_DF")
        self.lineEdit_DF_comment = QtWidgets.QLineEdit(self.PrepareData)
        self.lineEdit_DF_comment.setGeometry(QtCore.QRect(10, 40, 191, 23))
        self.lineEdit_DF_comment.setObjectName("lineEdit_DF_comment")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.PrepareData)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(10, 70, 581, 300))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.Vertical_Filters = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.Vertical_Filters.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.Vertical_Filters.setContentsMargins(0, 0, 0, 0)
        self.Vertical_Filters.setSpacing(8)
        self.Vertical_Filters.setObjectName("Vertical_Filters")
        self.gridLayout_DataFilters = QtWidgets.QGridLayout()
        self.gridLayout_DataFilters.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.gridLayout_DataFilters.setSpacing(5)
        self.gridLayout_DataFilters.setObjectName("gridLayout_DataFilters")
        self.pushButton_FilterDF_Lang_Polish = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.pushButton_FilterDF_Lang_Polish.setObjectName("pushButton_FilterDF_Lang_Polish")
        self.gridLayout_DataFilters.addWidget(self.pushButton_FilterDF_Lang_Polish, 1, 2, 1, 1)
        self.pushButton_FilterDF_TweetID = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.pushButton_FilterDF_TweetID.setToolTip("")
        self.pushButton_FilterDF_TweetID.setObjectName("pushButton_FilterDF_TweetID")
        self.gridLayout_DataFilters.addWidget(self.pushButton_FilterDF_TweetID, 1, 1, 1, 1)
        self.pushButton_FilterDF_by_NonEmptyKey = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.pushButton_FilterDF_by_NonEmptyKey.setEnabled(False)
        self.pushButton_FilterDF_by_NonEmptyKey.setObjectName("pushButton_FilterDF_by_NonEmptyKey")
        self.gridLayout_DataFilters.addWidget(self.pushButton_FilterDF_by_NonEmptyKey, 3, 3, 1, 1)
        self.pushButton_FilterDF_user = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.pushButton_FilterDF_user.setEnabled(False)
        self.pushButton_FilterDF_user.setToolTip("")
        self.pushButton_FilterDF_user.setObjectName("pushButton_FilterDF_user")
        self.gridLayout_DataFilters.addWidget(self.pushButton_FilterDF_user, 1, 0, 1, 1)
        self.lineEdit_FilterLangOther = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.lineEdit_FilterLangOther.setObjectName("lineEdit_FilterLangOther")
        self.gridLayout_DataFilters.addWidget(self.lineEdit_FilterLangOther, 4, 2, 1, 1)
        self.pushButton_filter_search_words = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.pushButton_filter_search_words.setObjectName("pushButton_filter_search_words")
        self.gridLayout_DataFilters.addWidget(self.pushButton_filter_search_words, 3, 1, 1, 1)
        self.pushButton_FilterDF_Lang_English = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.pushButton_FilterDF_Lang_English.setObjectName("pushButton_FilterDF_Lang_English")
        self.gridLayout_DataFilters.addWidget(self.pushButton_FilterDF_Lang_English, 2, 2, 1, 1)
        self.pushButton_FilterDF_Lang_Other = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.pushButton_FilterDF_Lang_Other.setObjectName("pushButton_FilterDF_Lang_Other")
        self.gridLayout_DataFilters.addWidget(self.pushButton_FilterDF_Lang_Other, 3, 2, 1, 1)
        self.pushButton_filter_search_words_anywhere = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.pushButton_filter_search_words_anywhere.setObjectName("pushButton_filter_search_words_anywhere")
        self.gridLayout_DataFilters.addWidget(self.pushButton_filter_search_words_anywhere, 3, 0, 1, 1)
        self.lineEdit_filterKeyinput = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.lineEdit_filterKeyinput.setObjectName("lineEdit_filterKeyinput")
        self.gridLayout_DataFilters.addWidget(self.lineEdit_filterKeyinput, 4, 3, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_DataFilters.addWidget(self.label_6, 0, 0, 1, 4)
        self.lineEdit_tweet_id = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.lineEdit_tweet_id.setObjectName("lineEdit_tweet_id")
        self.gridLayout_DataFilters.addWidget(self.lineEdit_tweet_id, 2, 1, 1, 1)
        self.lineEdit_user_input = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.lineEdit_user_input.setObjectName("lineEdit_user_input")
        self.gridLayout_DataFilters.addWidget(self.lineEdit_user_input, 2, 0, 1, 1)
        self.pushButton_find_retweets = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.pushButton_find_retweets.setEnabled(True)
        self.pushButton_find_retweets.setObjectName("pushButton_find_retweets")
        self.gridLayout_DataFilters.addWidget(self.pushButton_find_retweets, 1, 3, 1, 1)
        self.pushButton_filter_quoted_tweets = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.pushButton_filter_quoted_tweets.setEnabled(True)
        self.pushButton_filter_quoted_tweets.setObjectName("pushButton_filter_quoted_tweets")
        self.gridLayout_DataFilters.addWidget(self.pushButton_filter_quoted_tweets, 2, 3, 1, 1)
        self.lineEdit_filter_words = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.lineEdit_filter_words.setObjectName("lineEdit_filter_words")
        self.gridLayout_DataFilters.addWidget(self.lineEdit_filter_words, 4, 0, 1, 2)
        self.gridLayout_DataFilters.setColumnStretch(0, 2)
        self.gridLayout_DataFilters.setRowStretch(0, 1)
        self.Vertical_Filters.addLayout(self.gridLayout_DataFilters)
        self.checkBox_case_sensitivity = QtWidgets.QCheckBox(self.verticalLayoutWidget_3)
        self.checkBox_case_sensitivity.setChecked(False)
        self.checkBox_case_sensitivity.setObjectName("checkBox_case_sensitivity")
        self.Vertical_Filters.addWidget(self.checkBox_case_sensitivity)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        self.Vertical_Filters.addItem(spacerItem1)
        self.gridLayout_TimeFilters = QtWidgets.QGridLayout()
        self.gridLayout_TimeFilters.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.gridLayout_TimeFilters.setSpacing(5)
        self.gridLayout_TimeFilters.setObjectName("gridLayout_TimeFilters")
        self.spinBox_timezone = QtWidgets.QSpinBox(self.verticalLayoutWidget_3)
        self.spinBox_timezone.setMinimum(-12)
        self.spinBox_timezone.setMaximum(12)
        self.spinBox_timezone.setProperty("value", 1)
        self.spinBox_timezone.setObjectName("spinBox_timezone")
        self.gridLayout_TimeFilters.addWidget(self.spinBox_timezone, 3, 2, 1, 1)
        self.spinBox_timefilter_from_day = QtWidgets.QSpinBox(self.verticalLayoutWidget_3)
        self.spinBox_timefilter_from_day.setMaximum(31)
        self.spinBox_timefilter_from_day.setObjectName("spinBox_timefilter_from_day")
        self.gridLayout_TimeFilters.addWidget(self.spinBox_timefilter_from_day, 0, 4, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_TimeFilters.addWidget(self.label_10, 1, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_TimeFilters.addWidget(self.label_5, 2, 5, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_TimeFilters.addWidget(self.label_9, 0, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_TimeFilters.addWidget(self.label_4, 2, 4, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_TimeFilters.addWidget(self.label_7, 2, 6, 1, 1)
        self.spinBox_timefilter_from_hour = QtWidgets.QSpinBox(self.verticalLayoutWidget_3)
        self.spinBox_timefilter_from_hour.setMaximum(24)
        self.spinBox_timefilter_from_hour.setObjectName("spinBox_timefilter_from_hour")
        self.gridLayout_TimeFilters.addWidget(self.spinBox_timefilter_from_hour, 0, 5, 1, 1)
        self.spinBox_timefilter_to_hour = QtWidgets.QSpinBox(self.verticalLayoutWidget_3)
        self.spinBox_timefilter_to_hour.setMaximum(24)
        self.spinBox_timefilter_to_hour.setObjectName("spinBox_timefilter_to_hour")
        self.gridLayout_TimeFilters.addWidget(self.spinBox_timefilter_to_hour, 1, 5, 1, 1)
        self.spinBox_timefilter_to_day = QtWidgets.QSpinBox(self.verticalLayoutWidget_3)
        self.spinBox_timefilter_to_day.setMaximum(31)
        self.spinBox_timefilter_to_day.setObjectName("spinBox_timefilter_to_day")
        self.gridLayout_TimeFilters.addWidget(self.spinBox_timefilter_to_day, 1, 4, 1, 1)
        self.spinBox_timefilter_to_min = QtWidgets.QSpinBox(self.verticalLayoutWidget_3)
        self.spinBox_timefilter_to_min.setMaximum(60)
        self.spinBox_timefilter_to_min.setProperty("value", 10)
        self.spinBox_timefilter_to_min.setObjectName("spinBox_timefilter_to_min")
        self.gridLayout_TimeFilters.addWidget(self.spinBox_timefilter_to_min, 1, 6, 1, 1)
        self.spinBox_timefilter_from_min = QtWidgets.QSpinBox(self.verticalLayoutWidget_3)
        self.spinBox_timefilter_from_min.setMaximum(60)
        self.spinBox_timefilter_from_min.setObjectName("spinBox_timefilter_from_min")
        self.gridLayout_TimeFilters.addWidget(self.spinBox_timefilter_from_min, 0, 6, 1, 1)
        self.pushButton_filter_by_Age = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.pushButton_filter_by_Age.setEnabled(True)
        self.pushButton_filter_by_Age.setObjectName("pushButton_filter_by_Age")
        self.gridLayout_TimeFilters.addWidget(self.pushButton_filter_by_Age, 0, 0, 1, 1)
        self.pushButton_filter_by_Date = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.pushButton_filter_by_Date.setEnabled(True)
        self.pushButton_filter_by_Date.setObjectName("pushButton_filter_by_Date")
        self.gridLayout_TimeFilters.addWidget(self.pushButton_filter_by_Date, 1, 0, 1, 1)
        self.spinBox_timefilter_from_month = QtWidgets.QSpinBox(self.verticalLayoutWidget_3)
        self.spinBox_timefilter_from_month.setMaximum(12)
        self.spinBox_timefilter_from_month.setObjectName("spinBox_timefilter_from_month")
        self.gridLayout_TimeFilters.addWidget(self.spinBox_timefilter_from_month, 0, 3, 1, 1)
        self.spinBox_timefilter_from_year = QtWidgets.QSpinBox(self.verticalLayoutWidget_3)
        self.spinBox_timefilter_from_year.setMaximum(3000)
        self.spinBox_timefilter_from_year.setObjectName("spinBox_timefilter_from_year")
        self.gridLayout_TimeFilters.addWidget(self.spinBox_timefilter_from_year, 0, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_2.setObjectName("label_2")
        self.gridLayout_TimeFilters.addWidget(self.label_2, 2, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_8.setObjectName("label_8")
        self.gridLayout_TimeFilters.addWidget(self.label_8, 2, 3, 1, 1)
        self.spinBox_timefilter_to_year = QtWidgets.QSpinBox(self.verticalLayoutWidget_3)
        self.spinBox_timefilter_to_year.setMaximum(3000)
        self.spinBox_timefilter_to_year.setObjectName("spinBox_timefilter_to_year")
        self.gridLayout_TimeFilters.addWidget(self.spinBox_timefilter_to_year, 1, 2, 1, 1)
        self.spinBox_timefilter_to_month = QtWidgets.QSpinBox(self.verticalLayoutWidget_3)
        self.spinBox_timefilter_to_month.setMaximum(12)
        self.spinBox_timefilter_to_month.setObjectName("spinBox_timefilter_to_month")
        self.gridLayout_TimeFilters.addWidget(self.spinBox_timefilter_to_month, 1, 3, 1, 1)
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label.setObjectName("label")
        self.gridLayout_TimeFilters.addWidget(self.label, 3, 3, 1, 1)
        self.pushButton_set_current_time = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.pushButton_set_current_time.setStyleSheet("background-color: rgb(255, 210, 210);")
        self.pushButton_set_current_time.setObjectName("pushButton_set_current_time")
        self.gridLayout_TimeFilters.addWidget(self.pushButton_set_current_time, 1, 7, 1, 1)
        self.pushButton_reset_time = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.pushButton_reset_time.setStyleSheet("background-color: rgb(255, 210, 210);")
        self.pushButton_reset_time.setObjectName("pushButton_reset_time")
        self.gridLayout_TimeFilters.addWidget(self.pushButton_reset_time, 0, 7, 1, 1)
        self.gridLayout_TimeFilters.setColumnStretch(0, 2)
        self.gridLayout_TimeFilters.setColumnStretch(2, 1)
        self.gridLayout_TimeFilters.setColumnStretch(3, 1)
        self.gridLayout_TimeFilters.setColumnStretch(4, 1)
        self.gridLayout_TimeFilters.setColumnStretch(5, 1)
        self.gridLayout_TimeFilters.setColumnStretch(6, 1)
        self.gridLayout_TimeFilters.setRowStretch(0, 4)
        self.gridLayout_TimeFilters.setRowStretch(1, 4)
        self.Vertical_Filters.addLayout(self.gridLayout_TimeFilters)
        self.Vertical_Filters.setStretch(0, 1)
        self.Vertical_Filters.setStretch(3, 1)
        self.checkBox_filtration_keep_drop = QtWidgets.QCheckBox(self.PrepareData)
        self.checkBox_filtration_keep_drop.setEnabled(True)
        self.checkBox_filtration_keep_drop.setGeometry(QtCore.QRect(600, 150, 161, 23))
        self.checkBox_filtration_keep_drop.setChecked(True)
        self.checkBox_filtration_keep_drop.setObjectName("checkBox_filtration_keep_drop")
        self.pushButton_Request_Status = QtWidgets.QPushButton(self.PrepareData)
        self.pushButton_Request_Status.setGeometry(QtCore.QRect(610, 10, 151, 23))
        self.pushButton_Request_Status.setObjectName("pushButton_Request_Status")
        self.lineEdit_request_statusId = QtWidgets.QLineEdit(self.PrepareData)
        self.lineEdit_request_statusId.setGeometry(QtCore.QRect(610, 40, 151, 23))
        self.lineEdit_request_statusId.setObjectName("lineEdit_request_statusId")
        self.checkBox_filtration_continuous = QtWidgets.QCheckBox(self.PrepareData)
        self.checkBox_filtration_continuous.setGeometry(QtCore.QRect(600, 130, 181, 21))
        self.checkBox_filtration_continuous.setChecked(False)
        self.checkBox_filtration_continuous.setObjectName("checkBox_filtration_continuous")
        self.tabWidget.addTab(self.PrepareData, "")
        self.Model = QtWidgets.QWidget()
        self.Model.setObjectName("Model")
        self.pushButton_add_label1 = QtWidgets.QPushButton(self.Model)
        self.pushButton_add_label1.setGeometry(QtCore.QRect(500, 10, 81, 41))
        self.pushButton_add_label1.setObjectName("pushButton_add_label1")
        self.pushButton_add_label2 = QtWidgets.QPushButton(self.Model)
        self.pushButton_add_label2.setGeometry(QtCore.QRect(500, 60, 81, 41))
        self.pushButton_add_label2.setObjectName("pushButton_add_label2")
        self.pushButton_add_label3 = QtWidgets.QPushButton(self.Model)
        self.pushButton_add_label3.setGeometry(QtCore.QRect(500, 110, 81, 41))
        self.pushButton_add_label3.setObjectName("pushButton_add_label3")
        self.pushButton_add_label4 = QtWidgets.QPushButton(self.Model)
        self.pushButton_add_label4.setGeometry(QtCore.QRect(500, 160, 81, 41))
        self.pushButton_add_label4.setObjectName("pushButton_add_label4")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.Model)
        self.plainTextEdit.setGeometry(QtCore.QRect(610, 10, 91, 31))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(self.Model)
        self.plainTextEdit_2.setGeometry(QtCore.QRect(610, 60, 91, 31))
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.plainTextEdit_3 = QtWidgets.QPlainTextEdit(self.Model)
        self.plainTextEdit_3.setGeometry(QtCore.QRect(610, 110, 91, 31))
        self.plainTextEdit_3.setObjectName("plainTextEdit_3")
        self.plainTextEdit_4 = QtWidgets.QPlainTextEdit(self.Model)
        self.plainTextEdit_4.setGeometry(QtCore.QRect(610, 160, 91, 31))
        self.plainTextEdit_4.setObjectName("plainTextEdit_4")
        self.pushButton_add_label5 = QtWidgets.QPushButton(self.Model)
        self.pushButton_add_label5.setGeometry(QtCore.QRect(500, 210, 81, 41))
        self.pushButton_add_label5.setObjectName("pushButton_add_label5")
        self.plainTextEdit_5 = QtWidgets.QPlainTextEdit(self.Model)
        self.plainTextEdit_5.setGeometry(QtCore.QRect(610, 210, 91, 31))
        self.plainTextEdit_5.setObjectName("plainTextEdit_5")
        self.button_save_labeled_data = QtWidgets.QPushButton(self.Model)
        self.button_save_labeled_data.setGeometry(QtCore.QRect(10, 10, 141, 21))
        self.button_save_labeled_data.setObjectName("button_save_labeled_data")
        self.button_load_labeled_data = QtWidgets.QPushButton(self.Model)
        self.button_load_labeled_data.setGeometry(QtCore.QRect(10, 40, 141, 23))
        self.button_load_labeled_data.setObjectName("button_load_labeled_data")
        self.tableWidget_labeled_data = QtWidgets.QTableWidget(self.Model)
        self.tableWidget_labeled_data.setGeometry(QtCore.QRect(10, 70, 291, 261))
        self.tableWidget_labeled_data.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_labeled_data.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget_labeled_data.setRowCount(0)
        self.tableWidget_labeled_data.setColumnCount(2)
        self.tableWidget_labeled_data.setObjectName("tableWidget_labeled_data")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_labeled_data.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_labeled_data.setHorizontalHeaderItem(1, item)
        self.button_clear_labels_table = QtWidgets.QPushButton(self.Model)
        self.button_clear_labels_table.setGeometry(QtCore.QRect(160, 40, 141, 21))
        self.button_clear_labels_table.setObjectName("button_clear_labels_table")
        self.tabWidget.addTab(self.Model, "")
        self.Analyze = QtWidgets.QWidget()
        self.Analyze.setObjectName("Analyze")
        self.gridLayoutWidget = QtWidgets.QWidget(self.Analyze)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 10, 160, 80))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton_analyze_unique_vals = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_analyze_unique_vals.setEnabled(False)
        self.pushButton_analyze_unique_vals.setObjectName("pushButton_analyze_unique_vals")
        self.gridLayout_2.addWidget(self.pushButton_analyze_unique_vals, 0, 0, 1, 1)
        self.lineEdit_analyze_unique_key = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_analyze_unique_key.setObjectName("lineEdit_analyze_unique_key")
        self.gridLayout_2.addWidget(self.lineEdit_analyze_unique_key, 1, 0, 1, 1)
        self.pushButton_analyze_unique_vals_2 = QtWidgets.QPushButton(self.Analyze)
        self.pushButton_analyze_unique_vals_2.setEnabled(False)
        self.pushButton_analyze_unique_vals_2.setGeometry(QtCore.QRect(190, 20, 158, 25))
        self.pushButton_analyze_unique_vals_2.setObjectName("pushButton_analyze_unique_vals_2")
        self.tabWidget.addTab(self.Analyze, "")
        self.MainGrid.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.DisplayTweetsGrid = QtWidgets.QGridLayout()
        self.DisplayTweetsGrid.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.DisplayTweetsGrid.setSpacing(5)
        self.DisplayTweetsGrid.setObjectName("DisplayTweetsGrid")
        self.pushButton_drop_selection_from_WL = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_drop_selection_from_WL.setStyleSheet("background-color: rgb(225, 195, 138);")
        self.pushButton_drop_selection_from_WL.setObjectName("pushButton_drop_selection_from_WL")
        self.DisplayTweetsGrid.addWidget(self.pushButton_drop_selection_from_WL, 33, 0, 1, 2)
        self.pushButton_request_tweet_update = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_request_tweet_update.setStyleSheet("background-color: rgb(198, 251, 255);")
        self.pushButton_request_tweet_update.setObjectName("pushButton_request_tweet_update")
        self.DisplayTweetsGrid.addWidget(self.pushButton_request_tweet_update, 6, 0, 1, 2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.DisplayTweetsGrid.addItem(spacerItem2, 8, 0, 1, 1)
        self.pushButton_load_work_list = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_load_work_list.setObjectName("pushButton_load_work_list")
        self.DisplayTweetsGrid.addWidget(self.pushButton_load_work_list, 27, 1, 1, 1)
        self.pushButton_request_parent_tweets_from_df = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_request_parent_tweets_from_df.setStyleSheet("background-color: rgb(198, 251, 255);")
        self.pushButton_request_parent_tweets_from_df.setObjectName("pushButton_request_parent_tweets_from_df")
        self.DisplayTweetsGrid.addWidget(self.pushButton_request_parent_tweets_from_df, 5, 0, 1, 2)
        self.pushButton_PreviousTweet = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_PreviousTweet.setObjectName("pushButton_PreviousTweet")
        self.DisplayTweetsGrid.addWidget(self.pushButton_PreviousTweet, 21, 0, 1, 1)
        self.pushButton_ShowTweetAll = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_ShowTweetAll.setStyleSheet("background-color: rgb(215, 255, 223);")
        self.pushButton_ShowTweetAll.setObjectName("pushButton_ShowTweetAll")
        self.DisplayTweetsGrid.addWidget(self.pushButton_ShowTweetAll, 15, 0, 1, 2)
        self.pushButton_JumpToTweet = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_JumpToTweet.setObjectName("pushButton_JumpToTweet")
        self.DisplayTweetsGrid.addWidget(self.pushButton_JumpToTweet, 22, 0, 1, 1)
        self.pushButton_NextTweet = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_NextTweet.setObjectName("pushButton_NextTweet")
        self.DisplayTweetsGrid.addWidget(self.pushButton_NextTweet, 21, 1, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setEnabled(False)
        self.pushButton.setObjectName("pushButton")
        self.DisplayTweetsGrid.addWidget(self.pushButton, 7, 0, 1, 2)
        self.pushButton_ShowTweet = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_ShowTweet.setStyleSheet("background-color: rgb(215, 255, 223);")
        self.pushButton_ShowTweet.setObjectName("pushButton_ShowTweet")
        self.DisplayTweetsGrid.addWidget(self.pushButton_ShowTweet, 16, 0, 1, 2)
        self.pushButton_save_work_list = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_save_work_list.setObjectName("pushButton_save_work_list")
        self.DisplayTweetsGrid.addWidget(self.pushButton_save_work_list, 27, 0, 1, 1)
        self.lineEdit_JumpToTweet = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_JumpToTweet.setObjectName("lineEdit_JumpToTweet")
        self.DisplayTweetsGrid.addWidget(self.lineEdit_JumpToTweet, 22, 1, 1, 1)
        self.pushButton_open_in_browser = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_open_in_browser.setStyleSheet("background-color: rgb(215, 255, 223);")
        self.pushButton_open_in_browser.setObjectName("pushButton_open_in_browser")
        self.DisplayTweetsGrid.addWidget(self.pushButton_open_in_browser, 17, 0, 1, 2)
        self.pushButton_clear_work_list = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_clear_work_list.setStyleSheet("background-color: rgb(255, 64, 74);")
        self.pushButton_clear_work_list.setObjectName("pushButton_clear_work_list")
        self.DisplayTweetsGrid.addWidget(self.pushButton_clear_work_list, 34, 0, 1, 2)
        self.pushButton_add_selection_to_worklist = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_add_selection_to_worklist.setStyleSheet("background-color: rgb(184, 255, 190);")
        self.pushButton_add_selection_to_worklist.setObjectName("pushButton_add_selection_to_worklist")
        self.DisplayTweetsGrid.addWidget(self.pushButton_add_selection_to_worklist, 30, 0, 1, 2)
        self.pushButton_drop_current_tweet = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_drop_current_tweet.setEnabled(True)
        self.pushButton_drop_current_tweet.setStyleSheet("background-color: rgb(255, 215, 158);")
        self.pushButton_drop_current_tweet.setObjectName("pushButton_drop_current_tweet")
        self.DisplayTweetsGrid.addWidget(self.pushButton_drop_current_tweet, 31, 1, 1, 1)
        self.pushButton_add_to_work_list = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_add_to_work_list.setStyleSheet("background-color: rgb(124, 255, 110);")
        self.pushButton_add_to_work_list.setObjectName("pushButton_add_to_work_list")
        self.DisplayTweetsGrid.addWidget(self.pushButton_add_to_work_list, 31, 0, 1, 1)
        self.DisplayTweetsGrid.setColumnStretch(0, 1)
        self.MainGrid.addLayout(self.DisplayTweetsGrid, 0, 1, 1, 2)
        self.MainGrid.setColumnMinimumWidth(0, 300)
        self.MainGrid.setColumnMinimumWidth(1, 50)
        self.MainGrid.setRowMinimumHeight(0, 420)
        self.MainGrid.setColumnStretch(0, 20)
        self.MainGrid.setRowStretch(0, 1)
        self.MainGrid.setRowStretch(1, 1)
        self.MainGrid.setRowStretch(2, 1)
        self.MainGrid.setRowStretch(4, 1)
        self.gridLayout.addLayout(self.MainGrid, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1090, 20))
        self.menubar.setObjectName("menubar")
        self.actionMenuAuth = QtWidgets.QMenu(self.menubar)
        self.actionMenuAuth.setObjectName("actionMenuAuth")
        self.actionMenuRefresh_Gui = QtWidgets.QMenu(self.menubar)
        self.actionMenuRefresh_Gui.setObjectName("actionMenuRefresh_Gui")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuDebug = QtWidgets.QMenu(self.menubar)
        self.menuDebug.setObjectName("menuDebug")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionLogin = QtWidgets.QAction(MainWindow)
        self.actionLogin.setObjectName("actionLogin")
        self.actionWho_am_I = QtWidgets.QAction(MainWindow)
        self.actionWho_am_I.setObjectName("actionWho_am_I")
        self.actionTweet_Description = QtWidgets.QAction(MainWindow)
        self.actionTweet_Description.setObjectName("actionTweet_Description")
        self.actionRestart = QtWidgets.QAction(MainWindow)
        self.actionRestart.setObjectName("actionRestart")
        self.actionAction1 = QtWidgets.QAction(MainWindow)
        self.actionAction1.setObjectName("actionAction1")
        self.actionDebugUsers = QtWidgets.QAction(MainWindow)
        self.actionDebugUsers.setObjectName("actionDebugUsers")
        self.actionMenuAuth.addAction(self.actionLogin)
        self.actionMenuAuth.addAction(self.actionWho_am_I)
        self.actionMenuRefresh_Gui.addAction(self.actionRestart)
        self.menuHelp.addAction(self.actionTweet_Description)
        self.menuDebug.addAction(self.actionAction1)
        self.menuDebug.addAction(self.actionDebugUsers)
        self.menubar.addAction(self.actionMenuAuth.menuAction())
        self.menubar.addAction(self.actionMenuRefresh_Gui.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menubar.addAction(self.menuDebug.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.checkBox_wrap_console.setText(_translate("MainWindow", "Wrap Info"))
        self.checkBox_HideEmptyValues.setText(_translate("MainWindow", "Hide empty values"))
        self.checkBox_DisplayShortUserinfo.setText(_translate("MainWindow", "Short user info"))
        self.checkBox_DisplayShortQuoteStatus.setText(_translate("MainWindow", "Short quote and retweet"))
        self.checkBox_show_only_text.setText(_translate("MainWindow", "Show text only"))
        self.plainTextEdit_info.setPlainText(_translate("MainWindow", "None"))
        self.pushButton_export_DF.setToolTip(_translate("MainWindow", "Save DF to .csv File, Name is optional"))
        self.pushButton_export_DF.setText(_translate("MainWindow", "Export selected tweets to csv"))
        self.lineEdit_DF_comment.setToolTip(_translate("MainWindow", "(optional) You can set file name"))
        self.pushButton_FilterDF_Lang_Polish.setToolTip(_translate("MainWindow", "Filter DF, polish"))
        self.pushButton_FilterDF_Lang_Polish.setText(_translate("MainWindow", "Lang PL"))
        self.pushButton_FilterDF_TweetID.setText(_translate("MainWindow", "TweetId"))
        self.pushButton_FilterDF_by_NonEmptyKey.setToolTip(_translate("MainWindow", "Filter Tweets with non empty fields. Display fields in Help menu"))
        self.pushButton_FilterDF_by_NonEmptyKey.setText(_translate("MainWindow", "Find keys"))
        self.pushButton_FilterDF_user.setText(_translate("MainWindow", "User"))
        self.lineEdit_FilterLangOther.setToolTip(_translate("MainWindow", "input for Lang Button"))
        self.pushButton_filter_search_words.setToolTip(_translate("MainWindow", "<html><head/><body><p>Split words with \',\'.</p><p>To make sequential search split phrases with \';\'.</p></body></html>"))
        self.pushButton_filter_search_words.setText(_translate("MainWindow", "Find words"))
        self.pushButton_FilterDF_Lang_English.setToolTip(_translate("MainWindow", "Filter DF, english"))
        self.pushButton_FilterDF_Lang_English.setText(_translate("MainWindow", "Lang En"))
        self.pushButton_FilterDF_Lang_Other.setToolTip(_translate("MainWindow", "Filter DF, put language below"))
        self.pushButton_FilterDF_Lang_Other.setText(_translate("MainWindow", "Lang"))
        self.pushButton_filter_search_words_anywhere.setToolTip(_translate("MainWindow", "Find phrases or whole sentence. Use ; to filter tweets found with previouse phrase"))
        self.pushButton_filter_search_words_anywhere.setText(_translate("MainWindow", "Find phrases"))
        self.lineEdit_filterKeyinput.setToolTip(_translate("MainWindow", "Key input"))
        self.label_6.setText(_translate("MainWindow", "- - - - - - - - Find tweets - - - - - - - - "))
        self.pushButton_find_retweets.setToolTip(_translate("MainWindow", "Filter tweets that are retweets"))
        self.pushButton_find_retweets.setText(_translate("MainWindow", "Filter Retweets"))
        self.pushButton_filter_quoted_tweets.setToolTip(_translate("MainWindow", "Filter tweets that have quotes from other tweets"))
        self.pushButton_filter_quoted_tweets.setText(_translate("MainWindow", "Filter Quotes"))
        self.lineEdit_filter_words.setToolTip(_translate("MainWindow", "You can Add some comment to file name"))
        self.checkBox_case_sensitivity.setToolTip(_translate("MainWindow", "Ignore case sesnitivty"))
        self.checkBox_case_sensitivity.setText(_translate("MainWindow", "Case sensitive"))
        self.label_10.setText(_translate("MainWindow", "to:"))
        self.label_5.setText(_translate("MainWindow", "Hour"))
        self.label_9.setText(_translate("MainWindow", "from:"))
        self.label_4.setText(_translate("MainWindow", "Day"))
        self.label_7.setText(_translate("MainWindow", "Min"))
        self.pushButton_filter_by_Age.setToolTip(_translate("MainWindow", "Save DF to .csv File"))
        self.pushButton_filter_by_Age.setText(_translate("MainWindow", "Tweet Age"))
        self.pushButton_filter_by_Date.setToolTip(_translate("MainWindow", "Save DF to .csv File"))
        self.pushButton_filter_by_Date.setText(_translate("MainWindow", "Posting Date:"))
        self.label_2.setText(_translate("MainWindow", "Year"))
        self.label_8.setText(_translate("MainWindow", "Month"))
        self.label.setText(_translate("MainWindow", "Timezone"))
        self.pushButton_set_current_time.setText(_translate("MainWindow", "Current time"))
        self.pushButton_reset_time.setText(_translate("MainWindow", "Reset"))
        self.checkBox_filtration_keep_drop.setText(_translate("MainWindow", "Keep found"))
        self.pushButton_Request_Status.setToolTip(_translate("MainWindow", "Put Tweet id (status) number in box"))
        self.pushButton_Request_Status.setText(_translate("MainWindow", "Request tweet"))
        self.lineEdit_request_statusId.setToolTip(_translate("MainWindow", "Input index for Jump button."))
        self.checkBox_filtration_continuous.setToolTip(_translate("MainWindow", "Filters current list. Affects performance. Use only if you need to filter different things."))
        self.checkBox_filtration_continuous.setText(_translate("MainWindow", "Continuous Filtration"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.PrepareData), _translate("MainWindow", "Tweets"))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.PrepareData), _translate("MainWindow", "Analyze loaded DF"))
        self.pushButton_add_label1.setText(_translate("MainWindow", "Label 1"))
        self.pushButton_add_label1.setShortcut(_translate("MainWindow", "1"))
        self.pushButton_add_label2.setText(_translate("MainWindow", "Label 2"))
        self.pushButton_add_label2.setShortcut(_translate("MainWindow", "2"))
        self.pushButton_add_label3.setText(_translate("MainWindow", "Label 3"))
        self.pushButton_add_label3.setShortcut(_translate("MainWindow", "3"))
        self.pushButton_add_label4.setText(_translate("MainWindow", "Label 4"))
        self.pushButton_add_label4.setShortcut(_translate("MainWindow", "4"))
        self.plainTextEdit.setPlainText(_translate("MainWindow", "Positive"))
        self.plainTextEdit_2.setPlainText(_translate("MainWindow", "Negative"))
        self.plainTextEdit_3.setPlainText(_translate("MainWindow", "Neutral"))
        self.plainTextEdit_4.setPlainText(_translate("MainWindow", "Other"))
        self.pushButton_add_label5.setText(_translate("MainWindow", "Label 5"))
        self.pushButton_add_label5.setShortcut(_translate("MainWindow", "5"))
        self.plainTextEdit_5.setPlainText(_translate("MainWindow", "Other"))
        self.button_save_labeled_data.setText(_translate("MainWindow", "Save labeled data"))
        self.button_load_labeled_data.setText(_translate("MainWindow", "Load labeled data"))
        item = self.tableWidget_labeled_data.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "tweet_index"))
        item = self.tableWidget_labeled_data.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "label_num"))
        self.button_clear_labels_table.setText(_translate("MainWindow", "Clear Table"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Model), _translate("MainWindow", "Create datasets"))
        self.pushButton_analyze_unique_vals.setText(_translate("MainWindow", "Display unique vals"))
        self.lineEdit_analyze_unique_key.setToolTip(_translate("MainWindow", "(optional) You can Add some comment to file name"))
        self.pushButton_analyze_unique_vals_2.setText(_translate("MainWindow", "Display parent "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Analyze), _translate("MainWindow", "Analyze"))
        self.pushButton_drop_selection_from_WL.setToolTip(_translate("MainWindow", "Drop all tweet on list from work list"))
        self.pushButton_drop_selection_from_WL.setText(_translate("MainWindow", "Drop all from WL"))
        self.pushButton_request_tweet_update.setText(_translate("MainWindow", "Update tweets"))
        self.pushButton_load_work_list.setToolTip(_translate("MainWindow", "Use worklist as current tweet list"))
        self.pushButton_load_work_list.setText(_translate("MainWindow", "Get WL"))
        self.pushButton_request_parent_tweets_from_df.setText(_translate("MainWindow", "Get parent tweets"))
        self.pushButton_PreviousTweet.setToolTip(_translate("MainWindow", "Show previous Tweet from DF"))
        self.pushButton_PreviousTweet.setText(_translate("MainWindow", "<< Prev"))
        self.pushButton_ShowTweetAll.setText(_translate("MainWindow", "Get full tweet list"))
        self.pushButton_JumpToTweet.setToolTip(_translate("MainWindow", "Jumps to tweet from given index."))
        self.pushButton_JumpToTweet.setText(_translate("MainWindow", "Jump to"))
        self.pushButton_NextTweet.setToolTip(_translate("MainWindow", "Show next Tweet from DF"))
        self.pushButton_NextTweet.setText(_translate("MainWindow", "Next >>"))
        self.pushButton.setText(_translate("MainWindow", "Delete in DB"))
        self.pushButton_ShowTweet.setToolTip(_translate("MainWindow", "Show first Tweet from DF"))
        self.pushButton_ShowTweet.setText(_translate("MainWindow", "Show Tweet"))
        self.pushButton_save_work_list.setToolTip(_translate("MainWindow", "Saves current list as work list"))
        self.pushButton_save_work_list.setText(_translate("MainWindow", "Set WL"))
        self.lineEdit_JumpToTweet.setToolTip(_translate("MainWindow", "Input index for Jump button."))
        self.pushButton_open_in_browser.setText(_translate("MainWindow", "Open in browser"))
        self.pushButton_clear_work_list.setText(_translate("MainWindow", "Clear work list"))
        self.pushButton_add_selection_to_worklist.setToolTip(_translate("MainWindow", "Add all tweets from list to work list"))
        self.pushButton_add_selection_to_worklist.setText(_translate("MainWindow", "Add all to WL"))
        self.pushButton_drop_current_tweet.setToolTip(_translate("MainWindow", "Drop current tweet from work list and go to next one"))
        self.pushButton_drop_current_tweet.setText(_translate("MainWindow", "Drop from work list"))
        self.pushButton_add_to_work_list.setToolTip(_translate("MainWindow", "Add current tweet to work list and go to next one"))
        self.pushButton_add_to_work_list.setText(_translate("MainWindow", "Add to work List"))
        self.actionMenuAuth.setTitle(_translate("MainWindow", "Auth"))
        self.actionMenuRefresh_Gui.setTitle(_translate("MainWindow", "Restart"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.menuDebug.setTitle(_translate("MainWindow", "Debug"))
        self.actionLogin.setText(_translate("MainWindow", "Login"))
        self.actionWho_am_I.setText(_translate("MainWindow", "Who am I?"))
        self.actionTweet_Description.setText(_translate("MainWindow", "Tweet Keys"))
        self.actionRestart.setText(_translate("MainWindow", "Restart"))
        self.actionAction1.setText(_translate("MainWindow", "Action1"))
        self.actionDebugUsers.setText(_translate("MainWindow", "DebugUsers"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
